{{- if not .Values.secrets.encryption.existingSecret }}
{{- $encryptionKey := include "twenty.secretValue" (dict "context" . "secretName" (include "twenty.encryptionSecretName" .) "key" .Values.secrets.encryption.key "provided" .Values.secrets.encryption.encryptionKey "length" 32) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twenty.encryptionSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "twenty.labels" . | nindent 4 }}
    app.kubernetes.io/component: encryption
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.secrets.encryption.key }}: {{ $encryptionKey | quote }}
  {{- with .Values.secrets.encryption.fallbackEncryptionKey }}
  fallbackEncryptionKey: {{ . | quote }}
  {{- end }}
{{- end }}
