apiVersion: v2
name: twenty
description: Twenty CRM
type: application
version: 0.1.2
# renovate: image=twentycrm/twenty
appVersion: v2.45.8
home: https://twenty.com
sources:
  - https://github.com/twentyhq/twenty
maintainers:
  - name: ammarlakis
    url: https://github.com/ammarlakis
