apiVersion: v2
name: twenty
description: Twenty CRM
type: application
version: 0.1.0
appVersion: v2.12.0
home: https://twenty.com
sources:
  - https://github.com/twentyhq/twenty
maintainers:
  - name: Ammar Lakis
    url: https://github.com/ammarlakis
